<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

<!-- Mass properties -->
<xacro:property name="bridge_weight" value="3" />
<xacro:property name="trolley_weight" value="3" />

<xacro:macro name="inertial_box" params="mass x y z *origin">
    <inertial>
        <xacro:insert_block name="origin"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                izz="${(1/12) * mass * (x*x+y*y)}" />
    </inertial>
</xacro:macro>

<xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>



    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="grey">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

<!--  0 0 0 link -->
    <link name="ground_link">
    </link>

    <!-- length and width of base plate-->
    <xacro:property name="base_plate_length" value="3" />
    <xacro:property name="base_plate_width" value="2"/>

    <!-- making base plate 0.1 M thick-->
    <joint name="base_plate_joint" type="fixed">
        <parent link="ground_link"/>
        <child link="base_plate"/>
        <origin xyz ="${-base_plate_length/2} ${-base_plate_width/2} 0"/>
    </joint>

    <link name="base_plate">
        <visual>
            <origin xyz = "${base_plate_length/2} ${base_plate_width/2} 0.05"/>
            <geometry>
                <box size="${base_plate_length} ${base_plate_width} 0.1"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz = "${base_plate_length/2} ${base_plate_width/2} 0.05"/>
            <geometry>
                <box size="${base_plate_length} ${base_plate_width} 0.1"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1000" x="${base_plate_length}" y="${base_plate_width}" z="0.1">
            <origin xyz = "${base_plate_length/2} ${base_plate_width/2} 0.05"/>
        </xacro:inertial_box>

    </link>

    <!-- uprights-->

    <xacro:property name="hight" value="2" />
    <xacro:property name="upright_width" value="0.1" />

    <joint name="upright_joint" type="fixed">
        <parent link="base_plate"/>
        <child link="upright"/>
        <origin xyz ="0 0 0.1"/>
    </joint>

    <link name="upright">
        <visual>
            <origin xyz = "${upright_width/2} ${upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz = "${base_plate_length-upright_width/2} ${upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz = "${base_plate_length-upright_width/2} ${base_plate_width-upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz = "${upright_width/2} ${base_plate_width-upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz = "${base_plate_length/2} ${upright_width/2} ${hight-upright_width/2}"/>
            <geometry>
                <box size="${base_plate_length-2*upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz = "${base_plate_length/2} ${base_plate_width-upright_width/2} ${hight-upright_width/2}"/>
            <geometry>
                <box size="${base_plate_length-2*upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz = "${upright_width/2} ${upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
        </collision>
            
        <collision>
            <origin xyz = "${base_plate_length-upright_width/2} ${upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
        </collision>

        <collision>
            <origin xyz = "${base_plate_length-upright_width/2} ${base_plate_width-upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
        </collision>

        <collision>
            <origin xyz = "${upright_width/2} ${base_plate_width-upright_width/2} ${hight/2}"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${hight}"/>
            </geometry>
        </collision>

        <collision>
            <origin xyz = "${base_plate_length/2} ${upright_width/2} ${hight-upright_width/2}"/>
            <geometry>
                <box size="${base_plate_length-2*upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
        </collision>

        <collision>
            <origin xyz = "${base_plate_length/2} ${base_plate_width-upright_width/2} ${hight-upright_width/2}"/>
            <geometry>
                <box size="${base_plate_length-2*upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1000" x="${base_plate_length}" y="${base_plate_width}" z="${hight}">
            <origin xyz = "${base_plate_length/2} ${base_plate_width/2} ${hight/2}"/>
        </xacro:inertial_box>


    </link>

    <!-- BRIDGE-->
    <joint name="bridge_joint" type="prismatic">
        <origin xyz="0 ${base_plate_width/2} ${hight-upright_width}" rpy="0 0 0"/>
        <parent link="upright"/>
        <child link="bridge"/>
        <axis xyz="1 0 0"/>
        <limit lower="0.0" upper="${base_plate_length}" effort="100" velocity="4"/>
    </joint>
   
    <link name="bridge">
        <visual>
            <origin xyz="0 0 ${upright_width/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${upright_width} ${base_plate_width-2*upright_width} ${upright_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${upright_width/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${upright_width} ${base_plate_width-2*upright_width} ${upright_width}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${bridge_weight}"  x="${upright_width}" y="${base_plate_width-2*upright_width}" z="${upright_width}">
            <origin xyz="0 0 ${upright_width/2}" rpy="0 0 0"/>
        </xacro:inertial_box>


    </link>
<!-- Trolley-->
    <joint name="trolley_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="bridge"/>
        <child link="trolley"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-base_plate_width/2+upright_width}" upper="${base_plate_width/2-upright_width}" effort="100" velocity="4"/>

    </joint>

    <link name="trolley">
        <visual>
            <origin xyz="0 0 ${-upright_width/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${-upright_width/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${upright_width} ${upright_width} ${upright_width}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${trolley_weight}"  x="${upright_width}" y="${upright_width}" z="${upright_width}">
            <origin xyz="0 0 ${-upright_width/2}" rpy="0 0 0"/>
        </xacro:inertial_box>


    </link>

    <!-- Ball joint-->
    <!-- 3 revolute joints-->
    <!-- thedax, theday, rotation-->
    <joint name="thedax_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="trolley"/>
        <child link="bridge2x"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-60*pi/180}" upper="${60*pi/180}" effort="100" velocity="100"/>
        
    </joint>

    <link name="bridge2x">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        
    </link>

    <joint name="theday_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="bridge2x"/>
        <child link="x2y"/>
        <axis xyz="1 0 0"/>
        <limit lower="${-60*pi/180}" upper="${60*pi/180}" effort="100" velocity="100"/>
        
    </joint>

    <link name="x2y">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        
    </link>

    <joint name="rotation" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="x2y"/>
        <child link="cable"/>
        <axis xyz="0 0 1"/>
        
    </joint>
<!-- Cable-->
<xacro:property name="cable_length" value="1.2" />
    <link name="cable">
        <visual>
            <origin xyz="0.0 0.0 ${-cable_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.01" length="${cable_length}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${-cable_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.01" length="${cable_length}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${0.2}" length="${cable_length}" radius="0.01">
            <origin xyz="0.0 0.0 ${-cable_length/2}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>

        
    </link>

    
</robot>